package server;

import java.util.ArrayList;

public class Norway {
	/* Added for easy and portable fylke and kommune additions. 
	 * Stored in UTF-8 because of æøå.
	 */

ArrayList<String> kommuner;
ArrayList<String> fylker;

	public Norway()
	{
		kommuner = new ArrayList<String>();
		fylker = new ArrayList<String>();
		addFylker();
		addKommuner();
	}

public String getKommuneNumber(int i)
{
	return kommuner.get(i);
}

public String getFylkeNumber(int i)
{
	return fylker.get(i);
}

public int getNumberOfKommuner()
{
	return kommuner.size();
}

public int getNumberOfFylker()
{
	return fylker.size();
}

private void addFylker()
{
	this.fylker.add("Østfold");
	this.fylker.add("Vestfold");
	this.fylker.add("Vest-Agder");
	this.fylker.add("Troms - Romsa");
	this.fylker.add("Telemark");
	this.fylker.add("Sør-Trøndelag");
	this.fylker.add("Sogn og fjordane");
	this.fylker.add("Rogaland");
	this.fylker.add("Oslo");
	this.fylker.add("Oppland");
	this.fylker.add("Nord-Trøndelag");
	this.fylker.add("Nordland");
	this.fylker.add("Møre og Romsdal");
	this.fylker.add("Hordaland");
	this.fylker.add("Hedmark");
	this.fylker.add("Finnmark");
	this.fylker.add("Buskerud");
	this.fylker.add("Aust-Agder");
	this.fylker.add("Akershus");

}

private void addKommuner()
{
		this.kommuner.add("unknown");
		this.kommuner.add("Halden");
		this.kommuner.add("Halden");
		this.kommuner.add("Moss");
		this.kommuner.add("Sarpsborg");
		this.kommuner.add("Fredrikstad");
		this.kommuner.add("Hvaler");
		this.kommuner.add("Aremark");
		this.kommuner.add("Marker");
		this.kommuner.add("Rømskog");
		this.kommuner.add("Trøgstad");
		this.kommuner.add("Spydeberg");
		this.kommuner.add("Askim");
		this.kommuner.add("Eidsberg");
		this.kommuner.add("Skiptvet");
		this.kommuner.add("Rakkestad");
		this.kommuner.add("Råde");
		this.kommuner.add("Rygge");
		this.kommuner.add("Våler");
		this.kommuner.add("Hobøl");
		this.kommuner.add("Horten");
		this.kommuner.add("Holmestrand");
		this.kommuner.add("Tønsberg");
		this.kommuner.add("Sandefjord");
		this.kommuner.add("Larvik");
		this.kommuner.add("Svelvik");
		this.kommuner.add("Sande");
		this.kommuner.add("Hof");
		this.kommuner.add("Re");
		this.kommuner.add("Andebu");
		this.kommuner.add("Stokke");
		this.kommuner.add("Nøtterøy");
		this.kommuner.add("Tjøme");
		this.kommuner.add("Lardal");
		this.kommuner.add("Kristiansand");
		this.kommuner.add("Mandal");
		this.kommuner.add("Farsund");
		this.kommuner.add("Flekkefjord");
		this.kommuner.add("Vennesla");
		this.kommuner.add("Songdalen");
		this.kommuner.add("Søgne");
		this.kommuner.add("Marnardal");
		this.kommuner.add("Åseral");
		this.kommuner.add("Audnedal");
		this.kommuner.add("Lindesnes");
		this.kommuner.add("Lyngdal");
		this.kommuner.add("Hægebostad");
		this.kommuner.add("Kvinesdal");
		this.kommuner.add("Sirdal");
		this.kommuner.add("Harstad");
		this.kommuner.add("Tromsø");
		this.kommuner.add("Kvæfjord");
		this.kommuner.add("Skånland");
		this.kommuner.add("Ibestad");
		this.kommuner.add("Gratangen");
		this.kommuner.add("Loabák – Lavangen");
		this.kommuner.add("Bardu");
		this.kommuner.add("Salangen");
		this.kommuner.add("Målselv");
		this.kommuner.add("Sørreisa");
		this.kommuner.add("Dyrøy");
		this.kommuner.add("Tranøy");
		this.kommuner.add("Torsken");
		this.kommuner.add("Berg");
		this.kommuner.add("Lenvik");
		this.kommuner.add("Balsfjord");
		this.kommuner.add("Karlsøy");
		this.kommuner.add("Lyngen");
		this.kommuner.add("Storfjord – Omasvuotna – Omasvuono");
		this.kommuner.add("Gáivuotna – Kåfjord");
		this.kommuner.add("Skjervøy");
		this.kommuner.add("Nordreisa");
		this.kommuner.add("Kvænangen");
		this.kommuner.add("Porsgrunn");
		this.kommuner.add("Skien");
		this.kommuner.add("Notodden");
		this.kommuner.add("Siljan");
		this.kommuner.add("Bamble");
		this.kommuner.add("Kragerø");
		this.kommuner.add("Drangedal");
		this.kommuner.add("Nome");
		this.kommuner.add("Bø");
		this.kommuner.add("Sauherad");
		this.kommuner.add("Tinn");
		this.kommuner.add("Hjartdal");
		this.kommuner.add("Seljord");
		this.kommuner.add("Kviteseid");
		this.kommuner.add("Nissedal");
		this.kommuner.add("Fyresdal");
		this.kommuner.add("Tokke");
		this.kommuner.add("Vinje");
		this.kommuner.add("Trondheim");
		this.kommuner.add("Hemne");
		this.kommuner.add("Snillfjord");
		this.kommuner.add("Hitra");
		this.kommuner.add("Frøya");
		this.kommuner.add("Ørland");
		this.kommuner.add("Agdenes");
		this.kommuner.add("Rissa");
		this.kommuner.add("Bjugn");
		this.kommuner.add("Åfjord");
		this.kommuner.add("Roan");
		this.kommuner.add("Osen");
		this.kommuner.add("Oppdal");
		this.kommuner.add("Rennebu");
		this.kommuner.add("Meldal");
		this.kommuner.add("Orkdal");
		this.kommuner.add("Røros");
		this.kommuner.add("Holtålen");
		this.kommuner.add("Midtre Gauldal");
		this.kommuner.add("Melhus");
		this.kommuner.add("Skaun");
		this.kommuner.add("Klæbu");
		this.kommuner.add("Malvik");
		this.kommuner.add("Selbu");
		this.kommuner.add("Tydal");
		this.kommuner.add("Flora");
		this.kommuner.add("Gulen");
		this.kommuner.add("Solund");
		this.kommuner.add("Hyllestad");
		this.kommuner.add("Høyanger");
		this.kommuner.add("Vik");
		this.kommuner.add("Balestrand");
		this.kommuner.add("Leikanger");
		this.kommuner.add("Sogndal");
		this.kommuner.add("Aurland");
		this.kommuner.add("Lærdal");
		this.kommuner.add("Årdal");
		this.kommuner.add("Luster");
		this.kommuner.add("Askvoll");
		this.kommuner.add("Fjaler");
		this.kommuner.add("Gaular");
		this.kommuner.add("Jølster");
		this.kommuner.add("Førde");
		this.kommuner.add("Naustdal");
		this.kommuner.add("Bremanger");
		this.kommuner.add("Vågsøy");
		this.kommuner.add("Selje");
		this.kommuner.add("Eid");
		this.kommuner.add("Hornindal");
		this.kommuner.add("Gloppen");
		this.kommuner.add("Stryn");
		this.kommuner.add("Eigersund");
		this.kommuner.add("Sandnes");
		this.kommuner.add("Stavanger");
		this.kommuner.add("Haugesund");
		this.kommuner.add("Sokndal");
		this.kommuner.add("Lund");
		this.kommuner.add("Bjerkreim");
		this.kommuner.add("Hå");
		this.kommuner.add("Klepp");
		this.kommuner.add("Time");
		this.kommuner.add("Gjesdal");
		this.kommuner.add("Sola");
		this.kommuner.add("Randaberg");
		this.kommuner.add("Forsand");
		this.kommuner.add("Strand");
		this.kommuner.add("Hjelmeland");
		this.kommuner.add("Suldal");
		this.kommuner.add("Sauda");
		this.kommuner.add("Finnøy");
		this.kommuner.add("Rennesøy");
		this.kommuner.add("Kvitsøy");
		this.kommuner.add("Bokn");
		this.kommuner.add("Tysvær");
		this.kommuner.add("Karmøy");
		this.kommuner.add("Utsira");
		this.kommuner.add("Vindafjord");
		this.kommuner.add("Oslo");
		this.kommuner.add("Lillehammer");
		this.kommuner.add("Gjøvik");
		this.kommuner.add("Dovre");
		this.kommuner.add("Lesja");
		this.kommuner.add("Skjåk");
		this.kommuner.add("Lom");
		this.kommuner.add("Vågå");
		this.kommuner.add("Nord-Fron");
		this.kommuner.add("Sel");
		this.kommuner.add("Sør-Fron");
		this.kommuner.add("Ringebu");
		this.kommuner.add("Øyer");
		this.kommuner.add("Gausdal");
		this.kommuner.add("Østre Toten");
		this.kommuner.add("Vestre Toten");
		this.kommuner.add("Jevnaker");
		this.kommuner.add("Lunner");
		this.kommuner.add("Gran");
		this.kommuner.add("Søndre Land");
		this.kommuner.add("Nordre Land");
		this.kommuner.add("Sør-Aurdal");
		this.kommuner.add("Etnedal");
		this.kommuner.add("Nord-Aurdal");
		this.kommuner.add("Vestre Slidre");
		this.kommuner.add("Øystre Slidre");
		this.kommuner.add("Vang");
		this.kommuner.add("Steinkjer");
		this.kommuner.add("Namsos");
		this.kommuner.add("Meråker");
		this.kommuner.add("Stjørdal");
		this.kommuner.add("Frosta");
		this.kommuner.add("Leksvik");
		this.kommuner.add("Levanger");
		this.kommuner.add("Verdal");
		this.kommuner.add("Verran");
		this.kommuner.add("Namdalseid");
		this.kommuner.add("Snåase – Snåsa");
		this.kommuner.add("Lierne");
		this.kommuner.add("Raarvihke – Røyrvik");
		this.kommuner.add("Namsskogan");
		this.kommuner.add("Grong");
		this.kommuner.add("Høylandet");
		this.kommuner.add("Overhalla");
		this.kommuner.add("Fosnes");
		this.kommuner.add("Flatanger");
		this.kommuner.add("Vikna");
		this.kommuner.add("Nærøy");
		this.kommuner.add("Leka");
		this.kommuner.add("Inderøy");
		this.kommuner.add("Bodø");
		this.kommuner.add("Narvik");
		this.kommuner.add("Bindal");
		this.kommuner.add("Sømna");
		this.kommuner.add("Brønnøy");
		this.kommuner.add("Vega");
		this.kommuner.add("Vevelstad");
		this.kommuner.add("Herøy");
		this.kommuner.add("Alstahaug");
		this.kommuner.add("Leirfjord");
		this.kommuner.add("Vefsn");
		this.kommuner.add("Grane");
		this.kommuner.add("Hattfjelldal");
		this.kommuner.add("Dønna");
		this.kommuner.add("Nesna");
		this.kommuner.add("Hemnes");
		this.kommuner.add("Rana");
		this.kommuner.add("Lurøy");
		this.kommuner.add("Træna");
		this.kommuner.add("Rødøy");
		this.kommuner.add("Meløy");
		this.kommuner.add("Gildeskål");
		this.kommuner.add("Beiarn");
		this.kommuner.add("Saltdal");
		this.kommuner.add("Fauske");
		this.kommuner.add("Sørfold");
		this.kommuner.add("Steigen");
		this.kommuner.add("Hamarøy – Hábmer");
		this.kommuner.add("Divtasvuodna – Tysfjord");
		this.kommuner.add("Lødingen");
		this.kommuner.add("Tjeldsund");
		this.kommuner.add("Evenes");
		this.kommuner.add("Ballangen");
		this.kommuner.add("Røst");
		this.kommuner.add("Værøy");
		this.kommuner.add("Flakstad");
		this.kommuner.add("Vestvågøy");
		this.kommuner.add("Vågan");
		this.kommuner.add("Hadsel");
		this.kommuner.add("Bø");
		this.kommuner.add("Øksnes");
		this.kommuner.add("Sortland");
		this.kommuner.add("Andøy");
		this.kommuner.add("Moskenes");
		this.kommuner.add("Molde");
		this.kommuner.add("Ålesund");
		this.kommuner.add("Kristiansund");
		this.kommuner.add("Vanylven");
		this.kommuner.add("Sande");
		this.kommuner.add("Herøy");
		this.kommuner.add("Ulstein");
		this.kommuner.add("Hareid");
		this.kommuner.add("Volda");
		this.kommuner.add("Ørsta");
		this.kommuner.add("Ørskog");
		this.kommuner.add("Norddal");
		this.kommuner.add("Stranda");
		this.kommuner.add("Stordal");
		this.kommuner.add("Sykkylven");
		this.kommuner.add("Skodje");
		this.kommuner.add("Sula");
		this.kommuner.add("Giske");
		this.kommuner.add("Haram");
		this.kommuner.add("Vestnes");
		this.kommuner.add("Rauma");
		this.kommuner.add("Nesset");
		this.kommuner.add("Midsund");
		this.kommuner.add("Sandøy");
		this.kommuner.add("Aukra");
		this.kommuner.add("Fræna");
		this.kommuner.add("Eide");
		this.kommuner.add("Averøy");
		this.kommuner.add("Gjemnes");
		this.kommuner.add("Tingvoll");
		this.kommuner.add("Sunndal");
		this.kommuner.add("Surnadal");
		this.kommuner.add("Rindal");
		this.kommuner.add("Halsa");
		this.kommuner.add("Smøla");
		this.kommuner.add("Aure");
		this.kommuner.add("Bergen");
		this.kommuner.add("Etne");
		this.kommuner.add("Sveio");
		this.kommuner.add("Bømlo");
		this.kommuner.add("Stord");
		this.kommuner.add("Fitjar");
		this.kommuner.add("Tysnes");
		this.kommuner.add("Kvinnherad");
		this.kommuner.add("Jondal");
		this.kommuner.add("Odda");
		this.kommuner.add("Ullensvang");
		this.kommuner.add("Eidfjord");
		this.kommuner.add("Ulvik");
		this.kommuner.add("Granvin");
		this.kommuner.add("Voss");
		this.kommuner.add("Kvam");
		this.kommuner.add("Fusa");
		this.kommuner.add("Samnanger");
		this.kommuner.add("Os");
		this.kommuner.add("Austevoll");
		this.kommuner.add("Sund");
		this.kommuner.add("Fjell");
		this.kommuner.add("Askøy");
		this.kommuner.add("Vaksdal");
		this.kommuner.add("Modalen");
		this.kommuner.add("Osterøy");
		this.kommuner.add("Meland");
		this.kommuner.add("Øygarden");
		this.kommuner.add("Radøy");
		this.kommuner.add("Lindås");
		this.kommuner.add("Austrheim");
		this.kommuner.add("Fedje");
		this.kommuner.add("Masfjorden");
		this.kommuner.add("Kongsvinger");
		this.kommuner.add("Hamar");
		this.kommuner.add("Ringsaker");
		this.kommuner.add("Løten");
		this.kommuner.add("Stange");
		this.kommuner.add("Nord-Odal");
		this.kommuner.add("Sør-Odal");
		this.kommuner.add("Eidskog");
		this.kommuner.add("Grue");
		this.kommuner.add("Åsnes");
		this.kommuner.add("Våler");
		this.kommuner.add("Elverum");
		this.kommuner.add("Trysil");
		this.kommuner.add("Åmot");
		this.kommuner.add("Stor-Elvdal");
		this.kommuner.add("Rendalen");
		this.kommuner.add("Engerdal");
		this.kommuner.add("Tolga");
		this.kommuner.add("Tynset");
		this.kommuner.add("Alvdal");
		this.kommuner.add("Folldal");
		this.kommuner.add("Os");
		this.kommuner.add("Vardø");
		this.kommuner.add("Vadsø");
		this.kommuner.add("Hammerfest");
		this.kommuner.add("Guovdageaidnu – Kautokeino");
		this.kommuner.add("Alta");
		this.kommuner.add("Loppa");
		this.kommuner.add("Hasvik");
		this.kommuner.add("Kvalsund");
		this.kommuner.add("Måsøy");
		this.kommuner.add("Nordkapp");
		this.kommuner.add("Porsanger – Porsáŋgu – Porsanki");
		this.kommuner.add("Kárášjohka – Karasjok");
		this.kommuner.add("Lebesby");
		this.kommuner.add("Gamvik");
		this.kommuner.add("Berlevåg");
		this.kommuner.add("Deatnu – Tana");
		this.kommuner.add("Unjárga – Nesseby");
		this.kommuner.add("Båtsfjord");
		this.kommuner.add("Sør-Varanger");
		this.kommuner.add("Drammen");
		this.kommuner.add("Kongsberg");
		this.kommuner.add("Ringerike");
		this.kommuner.add("Hole");
		this.kommuner.add("Flå");
		this.kommuner.add("Nes");
		this.kommuner.add("Gol");
		this.kommuner.add("Hemsedal");
		this.kommuner.add("Ål");
		this.kommuner.add("Hol");
		this.kommuner.add("Sigdal");
		this.kommuner.add("Krødsherad");
		this.kommuner.add("Modum");
		this.kommuner.add("Øvre Eiker");
		this.kommuner.add("Nedre Eiker");
		this.kommuner.add("Lier");
		this.kommuner.add("Røyken");
		this.kommuner.add("Hurum");
		this.kommuner.add("Flesberg");
		this.kommuner.add("Rollag");
		this.kommuner.add("Nore og Uvdal");
		this.kommuner.add("Risør");
		this.kommuner.add("Grimstad");
		this.kommuner.add("Arendal");
		this.kommuner.add("Gjerstad");
		this.kommuner.add("Vegårshei");
		this.kommuner.add("Tvedestrand");
		this.kommuner.add("Froland");
		this.kommuner.add("Lillesand");
		this.kommuner.add("Birkenes");
		this.kommuner.add("Åmli");
		this.kommuner.add("Iveland");
		this.kommuner.add("Evje og Hornnes");
		this.kommuner.add("Evje");
		this.kommuner.add("Bygland");
		this.kommuner.add("Valle");
		this.kommuner.add("Bykle");
		this.kommuner.add("Vestby");
		this.kommuner.add("Ski");
		this.kommuner.add("Ås");
		this.kommuner.add("Frogn");
		this.kommuner.add("Nesodden");
		this.kommuner.add("Oppegård");
		this.kommuner.add("Bærum");
		this.kommuner.add("Asker");
		this.kommuner.add("Aurskog-Høland");
		this.kommuner.add("Sørum");
		this.kommuner.add("Fet");
		this.kommuner.add("Rælingen");
		this.kommuner.add("Enebakk");
		this.kommuner.add("Lørenskog");
		this.kommuner.add("Skedsmo");
		this.kommuner.add("Nittedal");
		this.kommuner.add("Gjerdrum");
		this.kommuner.add("Ullensaker");
		this.kommuner.add("Nes");
		this.kommuner.add("Eidsvoll");
		this.kommuner.add("Nannestad");
		this.kommuner.add("Hurdal");
	}
}
